export const mapList = [
    {
        name: "Bank",
        playlists: ["Ranked", "Unranked", "Quick Match"],
        layout: {
            "1F": [
                {
                    room: "ATMs",
                    shape: "poly",
                    coords: [
                        [468, 171],
                        [546, 171],
                        [546, 186],
                        [716, 186],
                        [716, 171],
                        [784, 171],
                        [784, 245],
                        [468, 245],
                    ],
                },
                {
                    room: "Lobby",
                    shape: "poly",
                    coords: [
                        [468, 251],
                        [787, 251],
                        [787, 370],
                        [737, 370],
                        [713, 377],
                        [694, 389],
                        [681, 408],
                        [675, 431],
                        [675, 508],
                        [630, 508],
                        [630, 538],
                        [468, 538],
                    ],
                },
                {
                    room: "Loan Office",
                    shape: "rect",
                    coords: [
                        [468, 546],
                        [629, 629],
                    ],
                },
                {
                    room: "Office Hallway",
                    shape: "poly",
                    coords: [
                        [635, 514],
                        [675, 514],
                        [675, 550],
                        [863, 550],
                        [863, 594],
                        [823, 594],
                        [823, 620],
                        [748, 620],
                        [748, 598],
                        [636, 598],
                    ],
                },
                {
                    room: "Main Stairway",
                    shape: "rect",
                    coords: [
                        [748, 620],
                        [823, 686],
                    ],
                },
                {
                    room: "Elevators",
                    shape: "rect",
                    coords: [
                        [640, 602],
                        [742, 652],
                    ]
                },
                {
                    room: "Tellers",
                    shape: "poly",
                    coords: [
                        [786, 375],
                        [786, 431],
                        [736, 489],
                        [736, 545],
                        [681, 545],
                        [681, 426],
                        [688, 407],
                        [701, 392],
                        [717, 381],
                        [738, 376],
                    ],
                },
                {
                    room: "Tellers' Office",
                    shape: "poly",
                    coords: [
                        [792, 324],
                        [875, 324],
                        [875, 438],
                        [864, 438],
                        [864, 504],
                        [806, 504],
                        [806, 545],
                        [741, 544],
                        [741, 491],
                        [792, 432],
                    ],
                },
                {
                    room: "Archives",
                    shape: "poly",
                    coords: [
                        [882, 324],
                        [1002, 324],
                        [1002, 485],
                        [869, 485],
                        [869, 444],
                        [882, 444],
                    ],
                },
                {
                    room: "Square",
                    shape: "poly",
                    coords: [
                        [1008, 324],
                        [1032, 324],
                        [1032, 368],
                        [1147, 368],
                        [1147, 440],
                        [1159, 440],
                        [1159, 470],
                        [1151, 470],
                        [1151, 530],
                        [1114, 530],
                        [1114, 435],
                        [1008, 484],
                    ],
                },
                {
                    room: "Square Stairs",
                    shape: "rect",
                    coords: [
                        [1032, 324],
                        [1119, 362],
                    ],
                },
                {
                    room: "Blue Stairs",
                    shape: "rect",
                    coords: [
                        [1119, 325],
                        [1147, 362],
                    ],
                },
                {
                    room: "Electrical Room",
                    shape: "poly",
                    coords: [
                        [1165, 440],
                        [1202, 440],
                        [1202, 530],
                        [1157, 530],
                        [1157, 476],
                        [1164, 476],
                    ],
                },
                {
                    room: "Staff Room",
                    shape: "poly",
                    coords: [
                        [991, 490],
                        [1108, 491],
                        [1108, 536],
                        [1157, 536],
                        [1157, 654],
                        [991, 654],
                    ],
                },
                {
                    room: "Open Area",
                    shape: "poly",
                    coords: [
                        [870, 550],
                        [985, 550],
                        [985, 711],
                        [830, 711],
                        [830, 601],
                        [870, 600],
                    ],
                },
                {
                    room: "Printer Room",
                    shape: "rect",
                    coords: [
                        [991, 661],
                        [1076, 711],
                    ],
                },
                {
                    room: "Admin Office",
                    shape: "rect",
                    coords: [
                        [870, 491],
                        [985, 545],
                    ],
                },
            ],
            "2F": [
                {
                    room: "ATMs",
                    shape: "poly",
                    coords: [
                        [468, 171],
                        [546, 171],
                        [546, 186],
                        [716, 186],
                        [716, 171],
                        [784, 171],
                        [784, 245],
                        [468, 245],
                    ],
                },
                {
                    room: "Lobby",
                    shape: "poly",
                    coords: [
                        [468, 251],
                        [787, 251],
                        [787, 370],
                        [737, 370],
                        [713, 377],
                        [694, 389],
                        [681, 408],
                        [675, 431],
                        [675, 508],
                        [630, 508],
                        [630, 538],
                        [468, 538],
                    ],
                },
                {
                    room: "Loan Office",
                    shape: "rect",
                    coords: [
                        [468, 546],
                        [629, 629],
                    ],
                },
                {
                    room: "Hallway",
                    shape: "poly",
                    coords: [
                        [635, 525],
                        [671, 525],
                        [671, 545],
                        [697, 569],
                        [964, 569],
                        [1010, 524],
                        [1010, 503],
                        [1045, 506],
                        [1045, 541],
                        [979, 607],
                        [979, 643],
                        [860, 643],
                        [860, 605],
                        [825, 605],
                        [825, 621],
                        [754, 621],
                        [754, 607],
                        [638, 607],
                    ],
                },
                {
                    room: "Square",
                    shape: "poly",
                    coords: [
                        [1011, 329],
                        [1042, 329],
                        [1042, 450],
                        [1116, 450],
                        [1116, 329],
                        [1187, 329],
                        [1187, 506],
                        [1011, 506],
                    ],
                },
                {
                    room: "Square Stairs",
                    shape: "rect",
                    coords: [
                        [1042, 329],
                        [1116, 369],
                    ],
                },
                {
                    room: "Stock Trading Room",
                    shape: "rect",
                    coords: [
                        [836, 648],
                        [980, 727],
                    ],
                },
                {
                    room: "Main Stairway",
                    shape: "rect",
                    coords: [
                        [754, 621],
                        [825, 697],
                    ],
                },
                {
                    room: "Elevator Shaft",
                    shape: "rect",
                    coords: [
                        [644, 612],
                        [690, 670],
                    ],
                },
                {
                    room: "Front Desk",
                    shape: "poly",
                    coords: [
                        [772, 370],
                        [772, 481],
                        [731, 481],
                        [731, 563],
                        [700, 563],
                        [676, 542],
                        [676, 427],
                        [684, 405],
                        [700, 385],
                        [722, 376],
                        [753, 370],
                    ],
                },
                {
                    room: "Executive Lounge",
                    shape: "rect",
                    coords: [
                        [779, 369],
                        [882, 480],
                    ],
                },
                {
                    room: "Conference Room",
                    shape: "rect",
                    coords: [
                        [737, 486],
                        [882, 564],
                    ],
                },
                {
                    room: "Janitor Closet",
                    shape: "poly",
                    coords: [
                        [888, 487],
                        [1005, 487],
                        [1005, 522],
                        [963, 563],
                        [888, 563],
                    ],
                },
                {
                    room: "CEO Office",
                    shape: "rect",
                    coords: [
                        [889, 331],
                        [1005, 480],
                    ],
                },
                {
                    room: "Executive Hallway",
                    shape: "rect",
                    coords: [
                        [798, 331],
                        [882, 363],
                    ],
                },
            ],
            "B": [
                {
                    room: "Main Stairway",
                    shape: "poly",
                    coords: [
                        [746, 595],
                        [797, 595],
                        [797, 624],
                        [812, 624],
                        [812, 681],
                        [746, 681],
                    ],
                },
                {
                    room: "Vault Lobby",
                    shape: "poly",
                    coords: [
                        [626, 520],
                        [730, 520],
                        [737, 552],
                        [797, 552],
                        [797, 589],
                        [626, 589],
                    ],
                },
                {
                    room: "Vault Entrance",
                    shape: "poly",
                    coords: [
                        [626, 452],
                        [666, 452],
                        [666, 443],
                        [703, 443],
                        [703, 452],
                        [731, 452],
                        [731, 515],
                        [626, 515],
                    ],
                },
                {
                    room: "Vault",
                    shape: "poly",
                    coords: [
                        [643, 328],
                        [811, 328],
                        [811, 426],
                        [703, 426],
                        [703, 443],
                        [666, 443],
                        [666, 424],
                        [643, 424],
                    ],
                },
                {
                    room: "Gold Vault",
                    shape: "poly",
                    coords: [
                        [818, 327],
                        [962, 327],
                        [962, 427],
                        [902, 427],
                        [902, 436],
                        [867, 436],
                        [867, 427],
                        [818, 427],
                    ],
                },
                {
                    room: "Secure Hallway",
                    shape: "rect",
                    coords: [
                        [863, 442],
                        [907, 547],
                    ],
                },
                {
                    room: "Secure Hallway",
                    shape: "rect",
                    coords: [
                        [803, 553],
                        [914, 589],
                    ],
                },
                {
                    room: "Elevators",
                    shape: "rect",
                    coords: [
                        [637, 595],
                        [740, 655],
                    ],
                },
                {
                    room: "Lockers",
                    shape: "poly",
                    coords: [
                        [737, 450],
                        [855, 450],
                        [855, 546],
                        [834, 546],
                        [834, 502],
                        [797, 502],
                        [797, 546],
                        [743, 546],
                        [737, 521],
                    ],
                },
                {
                    room: "Loading Docks",
                    shape: "poly",
                    coords: [
                        [804, 595],
                        [884, 595],
                        [884, 665],
                        [823, 665],
                        [823, 618],
                        [803, 618],
                    ],
                },
                {
                    room: "Bank Garage",
                    shape: "poly",
                    coords: [
                        [547, 666],
                        [736, 666],
                        [736, 692],
                        [823, 692],
                        [823, 665],
                        [885, 665],
                        [885, 823],
                        [547, 823],
                    ],
                },
                {
                    room: "Garage Ramp",
                    shape: "poly",
                    coords: [
                        [379, 621],
                        [453, 621],
                        [453, 640],
                        [460, 654],
                        [480, 665],
                        [547, 665],
                        [547, 731],
                        [473, 731],
                        [425, 720],
                        [400, 700],
                        [381, 664],
                        [379, 647],
                    ],
                },
                {
                    room: "CCTV Room",
                    shape: "poly",
                    coords: [
                        [915, 449],
                        [968, 449],
                        [968, 442],
                        [1026, 442],
                        [1026, 467],
                        [997, 467],
                        [997, 545],
                        [939, 545],
                        [939, 582],
                        [920, 582],
                        [920, 545],
                        [915, 545],
                    ],
                },
                {
                    room: "Server Room",
                    shape: "poly",
                    coords: [
                        [969, 375],
                        [1025, 375],
                        [1025, 364],
                        [1146, 364],
                        [1146, 474],
                        [1034, 474],
                        [1034, 436],
                        [969, 436],
                    ],
                },
                {
                    room: "Blue Stairs",
                    shape: "poly",
                    coords: [
                        [968, 328],
                        [1090, 328],
                        [1090, 360],
                        [1020, 360],
                        [1020, 368],
                        [968, 368],
                    ],
                },
                {
                    room: "Tunnel",
                    shape: "poly",
                    coords: [
                        [1094, 283],
                        [1134, 283],
                        [1134, 358],
                        [1090, 358],
                        [1090, 328],
                        [1081, 328],
                        [1081, 294],
                        [1094, 294],
                    ],
                },
                {
                    room: "Sewer",
                    shape: "poly",
                    coords: [
                        [1172, 64],
                        [1249, 64],
                        [1249, 283],
                        [1075, 283],
                        [1075, 253],
                        [1207, 253],
                        [1207, 90],
                        [1172, 90],
                    ],
                },
            ],
        },
    },
    {
        name: "Border",
        playlist: ["Ranked", "Unranked", "Quick Match"],
        layout: {
            "1F": [
                {
                    room: "Supply Room",
                    shape: "rect",
                    coords: [
                        [474, 374],
                        [576, 551],
                    ],
                },
                {
                    room: "Supply Corridor",
                    shape: "rect",
                    coords: [
                        [473, 555],
                        [577, 603],
                    ],
                },
                {
                    room: "Detention",
                    shape: "rect",
                    coords: [
                        [474, 606],
                        [577, 683],
                    ],
                },
                {
                    room: "Customs Inspection",
                    shape: "poly",
                    coords: [
                        [580, 454],
                        [628, 454],
                        [628, 532],
                        [704, 532],
                        [739, 495],
                        [739, 455],
                        [779, 455],
                        [804, 476],
                        [804, 683],
                        [580, 683],
                    ],
                },
                {
                    room: "Customs Desk",
                    shape: "poly",
                    coords: [
                        [632, 455],
                        [735, 455],
                        [735, 493],
                        [702, 529],
                        [632, 529],
                    ],
                },
                {
                    room: "Main Stairs",
                    shape: "rect",
                    coords: [
                        [580, 374],
                        [730, 451],
                    ],
                },
                {
                    room: "West Main",
                    shape: "rect",
                    coords: [
                        [516, 320],
                        [629, 371],
                    ],
                },
                {
                    room: "Ventilation Room",
                    shape: "rect",
                    coords: [
                        [517, 183],
                        [629, 316],
                    ],
                },
                {
                    room: "Server Room",
                    shape: "poly",
                    coords: [
                        [633, 183],
                        [779, 183],
                        [779, 267],
                        [729, 317],
                        [729, 370],
                        [633, 370],
                    ],
                },
                {
                    room: "Workshop",
                    shape: "poly",
                    coords: [
                        [782, 183],
                        [902, 183],
                        [902, 385],
                        [731, 385],
                        [731, 318],
                        [782, 267],
                    ],
                },
                {
                    room: "Main Lobby",
                    shape: "poly",
                    coords: [
                        [734, 385],
                        [906, 385],
                        [906, 333],
                        [954, 333],
                        [954, 483],
                        [906, 531],
                        [808, 531],
                        [808, 474],
                        [780, 451],
                        [734, 451],
                    ],
                },
                {
                    room: "Bathroom",
                    shape: "rect",
                    coords: [
                        [906, 183],
                        [1110, 329],
                    ],
                },
                {
                    room: "Tellers",
                    shape: "rect",
                    coords: [
                        [958, 333],
                        [1110, 481],
                    ],
                },
                {
                    room: "Passport Check",
                    shape: "rect",
                    coords: [
                        [807, 534],
                        [906, 683],
                    ],
                },
                {
                    room: "Waiting Room",
                    shape: "poly",
                    coords: [
                        [956, 485],
                        [1107, 485],
                        [1107, 683],
                        [911, 683],
                        [911, 532],
                    ],
                },
                {
                    room: "East Stairs",
                    shape: "rect",
                    coords: [
                        [1111, 478],
                        [1157, 683],
                    ],
                },
            ],
            "2F": [
                {
                    room: "East Stairs",
                    shape: "poly",
                    coords: [
                        [1084, 374],
                        [1126, 374],
                        [1126, 476],
                        [1167, 476],
                        [1167, 682],
                        [1128, 682],
                        [1128, 634],
                        [1084, 634],
                    ],
                },
                {
                    room: "Waiting Room",
                    shape: "rect",
                    coords: [
                        [919, 534],
                        [1079, 684],
                    ],
                },
                {
                    room: "Break Room",
                    shape: "rect",
                    coords: [
                        [743, 533],
                        [914, 684],
                    ],
                },
                {
                    room: "Security Room",
                    shape: "rect",
                    coords: [
                        [523, 453],
                        [738, 684],
                    ],
                },
                {
                    room: "Main Hallway",
                    shape: "poly",
                    coords: [
                        [739, 369],
                        [792, 369],
                        [792, 481],
                        [918, 481],
                        [918, 468],
                        [965, 468],
                        [965, 481],
                        [1080, 481],
                        [1080, 530],
                        [739, 530],
                    ],
                },
                {
                    room: "Main Stairs",
                    shape: "rect",
                    coords: [
                        [641, 371],
                        [738, 449],
                    ],
                },
                {
                    room: "Armory Lockers",
                    shape: "poly",
                    coords: [
                        [522, 176],
                        [792, 176],
                        [792, 365],
                        [737, 365],
                        [737, 296],
                        [634, 296],
                        [634, 367],
                        [522, 367],
                    ],
                },
                {
                    room: "Armory Desk",
                    shape: "rect",
                    coords: [
                        [640, 298],
                        [734, 367],
                    ],
                },
                {
                    room: "Archives",
                    shape: "poly",
                    coords: [
                        [796, 124],
                        [923, 124],
                        [923, 175],
                        [915, 175],
                        [915, 218],
                        [986, 218],
                        [986, 278],
                        [965, 317],
                        [796, 317],
                    ],
                },
                {
                    room: "Fountain",
                    shape: "rect",
                    coords: [
                        [796, 320],
                        [914, 478],
                    ],
                },
                {
                    room: "Offices",
                    shape: "poly",
                    coords: [
                        [991, 219],
                        [1081, 219],
                        [1081, 478],
                        [969, 478],
                        [969, 464],
                        [918, 464],
                        [918, 319],
                        [968, 319],
                        [991, 278],
                    ],
                },
                {
                    room: "East Balcony",
                    shape: "rect",
                    coords: [
                        [1085, 179],
                        [1126, 370],
                    ],
                },
                {
                    room: "North Balcony",
                    shape: "rect",
                    coords: [
                        [918, 179],
                        [1085, 216],
                    ],
                },
                {
                    room: "West Balcony",
                    shape: "poly",
                    coords: [
                        [474, 370],
                        [637, 370],
                        [637, 449],
                        [519, 449],
                        [519, 687],
                        [474, 730],
                    ],
                },
                {
                    room: "South Balcony",
                    shape: "poly",
                    coords: [
                        [519, 687],
                        [474, 730],
                        [1127, 730],
                        [1127, 687],
                        [1122, 687],
                        [1122, 639],
                        [1083, 639],
                        [1083, 687],
                    ],
                },
            ],
        }
    },
    {
        name: "Chalet",
        playlist: ["Ranked", "Unranked", "Quick Match", "New Comer"],
        layout: {
            "1F": [
                {
                    room: "Trophy Room",
                    shape: "poly",
                    coords: [
                        [850, 83],
                        [965, 83],
                        [965, 41],
                        [1073, 41],
                        [1073, 179],
                        [992, 179],
                        [992, 122],
                        [927, 122],
                        [927, 178],
                        [850, 178],
                    ],
                },
                {
                    room: "Trophy Stairs",
                    shape: "rect",
                    coords: [
                        [850, 42],
                        [962, 83],
                    ],
                },
                {
                    room: "Kitchen Hallway",
                    shape: "rect",
                    coords: [
                        [931, 125],
                        [990, 307],
                    ],
                },
                {
                    room: "Kitchen",
                    shape: "rect",
                    coords: [
                        [993, 183],
                        [1120, 376],
                    ],
                },
                {
                    room: "West Main Entrance",
                    shape: "poly",
                    coords: [
                        [796, 181],
                        [927, 181],
                        [927, 308],
                        [886, 308],
                        [886, 340],
                        [846, 340],
                        [846, 374],
                        [796, 374],
                    ],
                },
                {
                    room: "West-Main Stairs",
                    shape: "rect",
                    coords: [
                        [846, 340],
                        [886, 407],
                    ],
                },
                {
                    room: "Dining Room",
                    shape: "poly",
                    coords: [
                        [889, 311],
                        [990, 311],
                        [990, 379],
                        [1069, 379],
                        [1069, 525],
                        [906, 525],
                        [906, 407],
                        [889, 407],
                    ],
                },
                {
                    room: "Dining Hallway",
                    shape: "poly",
                    coords: [
                        [845, 409],
                        [903, 409],
                        [903, 543],
                        [859, 583],
                        [845, 583],
                    ],
                },
                {
                    room: "Gaming Room Hallway",
                    shape: "poly",
                    coords: [
                        [637, 530],
                        [845, 530],
                        [845, 583],
                        [710, 583],
                        [686, 607],
                        [686, 673],
                        [637, 673],
                    ],
                },
                {
                    room: "Mudroom",
                    shape: "rect",
                    coords: [
                        [564, 467],
                        [706, 528],
                    ],
                },
                {
                    room: "Library Stairs",
                    shape: "rect",
                    coords: [
                        [547, 530],
                        [637, 603],
                    ],
                },
                {
                    room: "Gaming Room",
                    shape: "poly",
                    coords: [
                        [547, 606],
                        [634, 606],
                        [634, 676],
                        [686, 676],
                        [686, 809],
                        [547, 809],
                    ],
                },
                {
                    room: "Bar Stock",
                    shape: "rect",
                    coords: [
                        [547, 812],
                        [719, 856],
                    ],
                },
                {
                    room: "Bar",
                    shape: "poly",
                    coords: [
                        [712, 586],
                        [842, 586],
                        [842, 809],
                        [690, 809],
                        [690, 608],
                    ],
                },
                {
                    room: "Fireplace",
                    shape: "poly",
                    coords: [
                        [905, 528],
                        [987, 528],
                        [987, 857],
                        [845, 857],
                        [845, 586],
                        [860, 586],
                        [905, 544],
                    ],
                },
                {
                    room: "Fireplace Stairs",
                    shape: "rect",
                    coords: [
                        [722, 812],
                        [845, 857],
                    ],
                },
            ],
            "2F": [
                {
                    room: "Mezzanine",
                    shape: "poly",
                    coords: [
                        [753, 613],
                        [990, 613],
                        [990, 682],
                        [829, 682],
                        [829, 742],
                        [846, 742],
                        [846, 871],
                        [753, 871],
                    ],
                },
                {
                    room: "Fireplace",
                    shape: "poly",
                    coords: [
                        [832, 685],
                        [990, 685],
                        [990, 871],
                        [848, 871],
                        [848, 740],
                        [832, 740],
                    ],
                },
                {
                    room: "Library",
                    shape: "poly",
                    coords: [
                        [541, 614],
                        [649, 614],
                        [649, 687],
                        [750, 687],
                        [750, 818],
                        [542, 818],
                    ],
                },
                {
                    room: "Library Entrance",
                    shape: "rect",
                    coords: [
                        [652, 614],
                        [749, 684],
                    ],
                },
                {
                    room: "Library Hallway",
                    shape: "rect",
                    coords: [
                        [650, 532],
                        [904, 611],
                    ],
                },
                {
                    room: "Library Stairs",
                    shape: "rect",
                    coords: [
                        [542, 532],
                        [650, 611],
                    ],
                },
                {
                    room: "Piano Room",
                    shape: "poly",
                    coords: [
                        [795, 313],
                        [991, 313],
                        [991, 377],
                        [905, 377],
                        [905, 529],
                        [795, 529],
                    ],
                },
                {
                    room: "Office",
                    shape: "poly",
                    coords: [
                        [907, 379],
                        [1077, 379],
                        [1077, 530],
                        [991, 530],
                        [991, 611],
                        [909, 611],
                    ],
                },
                {
                    room: "Master Bedroom",
                    shape: "poly",
                    coords: [
                        [930, 174],
                        [1127, 174],
                        [1127, 378],
                        [994, 378],
                        [994, 245],
                        [930, 245],
                    ],
                },
                {
                    room: "Solarium",
                    shape: "poly",
                    coords: [
                        [967, 33],
                        [1079, 33],
                        [1079, 172],
                        [849, 172],
                        [849, 122],
                        [946, 122],
                        [946, 80],
                        [967, 80],
                    ],
                },
                {
                    room: "Master Bathroom",
                    shape: "rect",
                    coords: [
                        [795, 175],
                        [927, 310],
                    ],
                },
                {
                    room: "Closet",
                    shape: "rect",
                    coords: [
                        [930, 249],
                        [991, 311],
                    ],
                },
                {
                    room: "Office Balcony",
                    shape: "rect",
                    coords: [
                        [997, 537],
                        [1076, 803],
                    ],
                },
                {
                    room: "Front Yard",
                    shape: "poly",
                    coords: [
                        [739, 179],
                        [788, 179],
                        [788, 527],
                        [716, 527],
                        [716, 464],
                        [739, 464],
                    ],
                },
                {
                    room: "Library Balcony",
                    shape: "poly",
                    coords: [
                        [491, 527],
                        [534, 527],
                        [534, 825],
                        [745, 825],
                        [745, 866],
                        [491, 866],
                    ],
                },
            ],
            "B": [
                {
                    room: "Library Stairs",
                    shape: "rect",
                    coords: [
                        [563, 528],
                        [644, 606],
                    ],
                },
                {
                    room: "Blue Hallway",
                    shape: "poly",
                    coords: [
                        [644, 565],
                        [816, 565],
                        [816, 460],
                        [863, 460],
                        [863, 612],
                        [729, 612],
                        [729, 638],
                        [647, 638],
                        [644, 606],
                    ],
                },
                {
                    room: "Snowmobile Garage",
                    shape: "poly",
                    coords: [
                        [733, 615],
                        [863, 615],
                        [863, 690],
                        [897, 690],
                        [897, 849],
                        [842, 849],
                        [842, 809],
                        [775, 809],
                        [775, 768],
                        [732, 768],
                    ],
                },
                {
                    room: "Fireplace Stairs",
                    shape: "poly",
                    coords: [
                        [732, 768],
                        [775, 768],
                        [775, 812],
                        [840, 812],
                        [840, 848],
                        [732, 848],
                    ],
                },
                {
                    room: "Storage Room",
                    shape: "rect",
                    coords: [
                        [901, 690],
                        [982, 807],
                    ],
                },
                {
                    room: "Wine Cellar",
                    shape: "poly",
                    coords: [
                        [866, 461],
                        [1063, 461],
                        [1063, 677],
                        [982, 677],
                        [982, 687],
                        [866, 687],
                    ],
                },
                {
                    room: "Basement Hallway",
                    shape: "poly",
                    coords: [
                        [923, 280],
                        [989, 280],
                        [989, 410],
                        [1112, 410],
                        [1112, 609],
                        [1067, 609],
                        [1067, 457],
                        [893, 457],
                        [893, 414],
                        [923, 414],
                    ],
                },
                {
                    room: "Car Garage",
                    shape: "poly",
                    coords: [
                        [845, 54],
                        [1002, 54],
                        [1002, 152],
                        [1024, 152],
                        [1024, 276],
                        [845, 276],
                    ],
                },
                {
                    room: "Main Garage Entrance",
                    shape: "rect",
                    coords: [
                        [1005, 53],
                        [1068, 149],
                    ],
                },
                {
                    room: "West-Main Stairs",
                    shape: "poly",
                    coords: [
                        [842, 324],
                        [887, 324],
                        [887, 415],
                        [893, 415],
                        [893, 457],
                        [842, 457],
                    ],
                },
                {
                    room: "Backyard Stairs",
                    shape: "poly",
                    coords: [
                        [1116, 311],
                        [1203, 311],
                        [1203, 356],
                        [1162, 356],
                        [1162, 468],
                        [1116, 468],
                    ],
                },
            ],
        }
    },
    {
        name: "Close Quarter",
        playlist: ["Team Deathmatch"],
        folder: '/images/maps/Close-Quarter/',
    },
    {
        name: "Clubhouse",
        playlist: ["Ranked", "Unranked", "Quick Match", "New Comer"],
        layout: {
            "1F": [
                {
                    room: "Junkyard Entrance",
                    shape: "rect",
                    coords: [
                        [313, 414],
                        [385, 531],
                    ],
                },
                {
                    room: "Side Entrance",
                    shape: "poly",
                    coords: [
                        [337, 625],
                        [473, 625],
                        [473, 678],
                        [407, 678],
                        [407, 693],
                        [337, 693],
                    ],
                },
                {
                    room: "Changing Room",
                    shape: "rect",
                    coords: [
                        [475, 607],
                        [600, 679],
                    ],
                },
                {
                    room: "Strip Club",
                    shape: "poly",
                    coords: [
                        [387, 414],
                        [574, 414],
                        [574, 505],
                        [599, 505],
                        [599, 605],
                        [474, 605],
                        [474, 624],
                        [387, 624],
                    ],
                },
                {
                    room: "Western Hallway",
                    shape: "poly",
                    coords: [
                        [510, 218],
                        [558, 218],
                        [558, 292],
                        [646, 292],
                        [646, 338],
                        [622, 338],
                        [622, 369],
                        [560, 369],
                        [560, 413],
                        [510, 413],
                    ],
                },
                {
                    room: "Toilets",
                    shape: "rect",
                    coords: [
                        [561, 218],
                        [693, 290],
                    ],
                },
                {
                    room: "Pool Table",
                    shape: "poly",
                    coords: [
                        [624, 341],
                        [647, 341],
                        [682, 377],
                        [682, 503],
                        [576, 503],
                        [576, 371],
                        [624, 371],
                    ],
                },
                {
                    room: "Bar",
                    shape: "poly",
                    coords: [
                        [647, 292],
                        [833, 292],
                        [833, 472],
                        [684, 472],
                        [684, 375],
                        [647, 339],
                    ],
                },
                {
                    room: "Stage",
                    shape: "poly",
                    coords: [
                        [834, 292],
                        [974, 292],
                        [974, 433],
                        [942, 433],
                        [903, 462],
                        [903, 472],
                        [834, 472],
                    ],
                },
                {
                    room: "Lobby",
                    shape: "poly",
                    coords: [
                        [943, 436],
                        [974, 436],
                        [974, 570],
                        [905, 570],
                        [905, 463],
                    ],
                },
                {
                    room: "Front Porch",
                    shape: "rect",
                    coords: [
                        [685, 475],
                        [901, 545],
                    ],
                },
                {
                    room: "Lounge",
                    shape: "poly",
                    coords: [
                        [976, 424],
                        [1194, 424],
                        [1194, 526],
                        [1109, 526],
                        [1109, 553],
                        [976, 553],
                    ],
                },
                {
                    room: "Eastern Stairs",
                    shape: "rect",
                    coords: [
                        [1152, 358],
                        [1194, 424],
                    ]
                },
                {
                    room: "Stock Room",
                    shape: "poly",
                    coords: [
                        [976, 307],
                        [1031, 307],
                        [1031, 292],
                        [1166, 292],
                        [1194, 322],
                        [1194, 357],
                        [1149, 357],
                        [1149, 422],
                        [976, 422],
                    ],
                },
                {
                    room: "Garage Storage",
                    shape: "poly",
                    coords: [
                        [1223, 383],
                        [1287, 383],
                        [1287, 523],
                        [1198, 523],
                        [1198, 463],
                        [1223, 463],
                    ],
                },
                {
                    room: "Blue Stairs",
                    shape: "rect",
                    coords: [
                        [1198, 383],
                        [1198, 463],
                    ],
                },
                {
                    room: "Garage",
                    shape: "poly",
                    coords: [
                        [976, 555],
                        [1111, 555],
                        [1111, 528],
                        [1149, 528],
                        [1149, 711],
                        [1171, 711],
                        [1171, 752],
                        [1149, 752],
                        [1149, 782],
                        [976, 782],
                    ],
                },
                {
                    room: "Central Hallway",
                    shape: "poly",
                    coords: [
                        [696, 214],
                        [778, 214],
                        [778, 244],
                        [951, 244],
                        [951, 290],
                        [696, 290],
                    ],
                },
                {
                    room: "Central Stairs",
                    shape: "rect",
                    coords: [
                        [696, 119],
                        [778, 214],
                    ],
                },
                {
                    room: "Kitchen",
                    shape: "poly",
                    coords: [
                        [861, 102],
                        [951, 102],
                        [951, 243],
                        [780, 243],
                        [780, 144],
                        [816, 144],
                        [816, 119],
                        [861, 119],
                    ],
                },
                {
                    room: "Kitchen Entrance",
                    shape: "rect",
                    coords: [
                        [780, 63],
                        [858, 117],
                    ],
                },
            ],
            "2F": [
                {
                    room: "Central Stairs",
                    shape: "rect",
                    coords: [
                        [708, 118],
                        [791, 220],
                    ],
                },
                {
                    room: "Bedroom Hallway",
                    shape: "poly",
                    coords: [
                        [645, 220],
                        [835, 220],
                        [835, 265],
                        [695, 265],
                        [695, 341],
                        [645, 341],
                    ],
                },
                {
                    room: "Logistic Office",
                    shape: "poly",
                    coords: [
                        [793, 101],
                        [970, 101],
                        [970, 246],
                        [889, 246],
                        [889, 218],
                        [793, 218],
                    ],
                },
                {
                    room: "Secret Stash",
                    shape: "rect",
                    coords: [
                        [838, 200],
                        [888, 263],
                    ],
                },
                {
                    room: "Bedroom",
                    shape: "poly",
                    coords: [
                        [793, 267],
                        [890, 267],
                        [890, 380],
                        [871, 380],
                        [871, 480],
                        [744, 480],
                        [744, 343],
                        [793, 307],
                    ],
                },
                {
                    room: "Bathroom",
                    shape: "poly",
                    coords: [
                        [698, 267],
                        [791, 267],
                        [791, 307],
                        [744, 340],
                        [698, 340],
                    ],
                },
                {
                    room: "Gym",
                    shape: "rect",
                    coords: [
                        [645, 343],
                        [738, 479],
                    ],
                },
                {
                    room: "Construction",
                    shape: "poly",
                    coords: [
                        [891, 251],
                        [970, 251],
                        [970, 295],
                        [993, 295],
                        [993, 459],
                        [873, 459],
                        [873, 382],
                        [891, 382],
                    ],
                },
                {
                    room: "Cash Room",
                    shape: "poly",
                    coords: [
                        [993, 295],
                        [1110, 295],
                        [1110, 374],
                        [1131, 400],
                        [1131, 460],
                        [1054, 460],
                        [1054, 438],
                        [993, 438],
                    ],
                },
                {
                    room: "CCTV Room",
                    shape: "poly",
                    coords: [
                        [994, 439],
                        [1054, 439],
                        [1054, 460],
                        [1134, 460],
                        [1134, 455],
                        [1179, 455],
                        [1179, 531],
                        [1172, 531],
                        [1172, 563],
                        [994, 563],
                    ],
                },
                {
                    room: "Eastern Stairs",
                    shape: "poly",
                    coords: [
                        [1116, 295],
                        [1187, 295],
                        [1218, 327],
                        [1218, 407],
                        [1179, 407],
                        [1179, 454],
                        [1133, 454],
                        [1133, 398],
                        [1116, 375],
                    ],
                },
                {
                    room: "Eastern Sub-roof",
                    shape: "poly",
                    coords: [
                        [1223, 379],
                        [1300, 379],
                        [1300, 527],
                        [1183, 527],
                        [1183, 411],
                        [1223, 411],
                    ],
                },
                {
                    room: "Garage",
                    shape: "rect",
                    coords: [
                        [995, 565],
                        [1172, 798],
                    ],
                },
                {
                    room: "Balcony",
                    shape: "rect",
                    coords: [
                        [503, 213],
                        [639, 408],
                    ],
                },
                {
                    room: "Central Sub-roof",
                    shape: "poly",
                    coords: [
                        [640, 486],
                        [878, 486],
                        [878, 462],
                        [991, 462],
                        [991, 578],
                        [901, 578],
                        [901, 586],
                        [680, 586],
                        [680, 511],
                        [640, 511],
                    ],
                },
                {
                    room: "Trash",
                    shape: "rect",
                    coords: [
                        [976, 242],
                        [1070, 287],
                    ],
                },
            ],
            "B": [
                {
                    room: "Central Stairs",
                    shape: "poly",
                    coords: [
                        [678, 123],
                        [759, 123],
                        [759, 237],
                        [717, 237],
                        [717, 298],
                        [678, 298],
                    ],
                },
                {
                    room: "Basement Hallway",
                    shape: "poly",
                    coords: [
                        [720, 240],
                        [951, 240],
                        [951, 284],
                        [770, 284],
                        [770, 383],
                        [720, 383],
                    ],
                },
                {
                    room: "Memorial Room",
                    shape: "rect",
                    coords: [
                        [677, 385],
                        [821, 478],
                    ],
                },
                {
                    room: "Church",
                    shape: "poly",
                    coords: [
                        [775, 286],
                        [951, 286],
                        [951, 479],
                        [823, 479],
                        [823, 383],
                        [775, 383],
                    ],
                },
                {
                    room: "Arsenal Room",
                    shape: "poly",
                    coords: [
                        [762, 122],
                        [840, 122],
                        [840, 105],
                        [932, 105],
                        [932, 138],
                        [983, 138],
                        [1034, 148],
                        [1090, 148],
                        [1090, 338],
                        [1068, 338],
                        [1068, 341],
                        [953, 341],
                        [953, 238],
                        [762, 238],
                    ],
                },
                {
                    room: "Escape Tunnel",
                    shape: "poly",
                    coords: [
                        [977, 0],
                        [1026, 0],
                        [1028, 8],
                        [1015, 13],
                        [1023, 32],
                        [1019, 44],
                        [1007, 53],
                        [1000, 77],
                        [984, 81],
                        [981, 88],
                        [1005, 113],
                        [1015, 136],
                        [989, 133],
                        [967, 131],
                        [946, 89],
                        [952, 62],
                        [974, 33],
                        [981, 19],
                        [976, 0],
                    ],
                },
                {
                    room: "Utility Room",
                    shape: "poly",
                    coords: [
                        [957, 343],
                        [1068, 343],
                        [1068, 624],
                        [1030, 624],
                        [1030, 479],
                        [957, 479],
                    ],
                },
                {
                    room: "Oil Pit",
                    shape: "poly",
                    coords: [
                        [970, 620],
                        [1097, 620],
                        [1097, 651],
                        [1084, 651],
                        [1084, 687],
                        [1097, 687],
                        [1097, 719],
                        [970, 718],
                        [970, 687],
                        [984, 687],
                        [984, 651],
                        [970, 651],
                    ],
                },
                {
                    room: "Blue Stairs",
                    shape: "poly",
                    coords: [
                        [1068, 383],
                        [1221, 383],
                        [1221, 460],
                        [1181, 460],
                        [1181, 420],
                        [1068, 420],
                    ],
                },
            ],
        }
    },
    {
        name: "Coastline",
        playlist: ["Ranked", "Unranked", "Quick Match", "New Comer", "Team Deathmatch"],
        folder: '/images/maps/Coastline/',
    },
    {
        name: "Consulate",
        playlist: ["Ranked", "Unranked", "Quick Match"],
        folder: '/images/maps/Consulate/',
    },
    {
        name: "Emerald Plains",
        playlist: ["Ranked", "Unranked", "Quick Match", "Team Deathmatch"],
        folder: '/images/maps/Emerald-Plains/',
    },
    {
        name: "Favela",
        playlist: ["Ranked", "Unranked", "Quick Match", "Team Deathmatch"],
        folder: '/images/maps/Favela/',
    },
    {
        name: "Fortress",
        playlist: ["Quick Match"],
        folder: '/images/maps/Fortress/',
    },
    {
        name: "Hereford Base",
        playlist: ["Quick Match"],
        folder: '/images/maps/Hereford-Base/',
    },
    {
        name: "House",
        playlist: ["Quick Match"],
        folder: '/images/maps/House/',
    },
    {
        name: "Kafe Dostoyevsky",
        playlist: ["Ranked", "Unranked", "Quick Match", "New Comer"],
        folder: '/images/maps/Kafe-Dostoyevsky/',
    },
    {
        name: "Kanal",
        playlist: ["Ranked", "Unranked", "Quick Match"],
        folder: '/images/maps/Kanal/',
    },
    {
        name: "Oregon",
        playlist: ["Ranked", "Unranked", "Quick Match", "New Comer"],
        folder: '/images/maps/Oregon/',
    },
    {
        name: "Outback", 
        playlist: ["Ranked", "Unranked", "Quick Match", "New Comer"],
        folder: '/images/maps/Outback/',
    },
    {
        name: "Presidential Plane",
        playlist: ["Quick Match"],
        folder: '/images/maps/Presidential-Plane/',
    },
    {
        name: "Skyscraper",
        playlist: ["Ranked", "Unranked", "Quick Match", "Team Deathmatch"],
        folder: '/images/maps/Skyscraper/',
    },
    {
        name: "Stadium Bravo",
        playlist: ["Ranked", "Unranked", "Quick Match", "Team Deathmatch", "New Comer"],
        folder: '/images/maps/Stadium-Bravo/',
    },
    {
        name: "Theme Park",
        playlist: ["Ranked", "Unranked", "Quick Match", "Team Deathmatch"],
        folder: '/images/maps/Theme-Park/',
    },
    {
        name: "Tower",
        playlist: ["Quick Match"],
        folder: '/images/maps/Tower/',
    },
    {
        name: "Villa",
        playlist: ["Ranked", "Unranked", "Quick Match", "Team Deathmatch"],
        folder: '/images/maps/Villa/',
    },
    {
        name: "Yacht",
        playlist: ["Quick Match"],
        folder: '/images/maps/Yacht/',
    },
]