export const operatorList = [
    {
        name: 'Ace',
        team: 'Attack',
        ability: 'S.E.L.M.A. Aqua Breacher',
        health: 2,
    }, 
    {
        name: 'Alibi',
        team: 'Defend',
        ability: 'Prisma',
        health: 1,
    },
    {
        name: 'Amaru',
        team: 'Attack',
        ability: 'Garra Hook',
        health: 2,
    },
    {
        name: 'Aruni',
        team: 'Defend',
        ability: 'Surya Laser Gate',
        health: 2,
    }, 
    {
        name: 'Ash',
        team: 'Attack',
        ability: 'Breaching Round',
        health: 1,
    },
    {
        name: 'Azami',
        team: 'Defend',
        ability: 'Kiba Barrier',
        health: 2,
    },
    {
        name: 'Bandit',
        team: 'Defend',
        ability: 'Shock Wire',
        health: 1,
    }, 
    {
        name: 'Blackbeard',
        team: 'Attack',
        ability: 'Rifle-Shield',
        health: 2,
    },
    {
        name: 'Blitz',
        team: 'Attack',
        ability: 'Flash Shield',
        health: 2,
    },
    {
        name: 'Buck',
        team: 'Attack',
        ability: 'Skeleton Key',
        health: 2,
    },
    {
        name: 'Capitao',
        team: 'Attack',
        ability: 'Tactical Crossbow',
        health: 1,
    },
    {
        name: 'Castle',
        team: 'Defend',
        ability: 'Armor Panel',
        health: 2,
    },
    {
        name: 'Caveira',
        team: 'Defend',
        ability: 'Silent Step',
        health: 1,
    },
    {
        name: 'Clash',
        team: 'Defend',
        ability: 'CCE Shield',
        health: 3,
    },
    {
        name: 'Doc',
        team: 'Defend',
        ability: 'Stim Pistol',
        health: 3,
    },
    {
        name: 'Dokkaebi',
        team: 'Attack',
        ability: 'Logic Bomb',
        health: 2,
    },
    {
        name: 'Echo',
        team: 'Defend',
        ability: 'Yokai',
        health: 3,
    },
    {
        name: 'Ela',
        team: 'Defend',
        ability: 'Grzmot Mine',
        health: 1,
    },
    {
        name: 'Finka',
        team: 'Attack',
        ability: 'Adrenal Surge',
        health: 2,
    },
    {
        name: 'Flores',
        team: 'Attack',
        ability: 'RCE-Ratero Charge',
        health: 2,
    },
    {
        name: 'Frost',
        team: 'Defend',
        ability: 'Welcome Mat',
        health: 2,
    },
    {
        name: 'Fuze',
        team: 'Attack',
        ability: 'Cluster Charge',
        health: 3,
    },
    {
        name: 'Glaz',
        team: 'Attack',
        ability: 'Thermal Flip Scope',
        health: 1,
    },
    {
        name: 'Goyo',
        team: 'Defend',
        ability: 'Volcan Canister',
        health: 2,
    },
    {
        name: 'Gridlock',
        team: 'Attack',
        ability: 'Trax Stinger',
        health: 3,
    },
    {
        name: 'Grim',
        team: 'Attack',
        ability: 'Kawan Hive Launcher',
        health: 1,
    },
    {
        name: 'Hibana',
        team: 'Attack',
        ability: 'X-KAIROS',
        health: 1,
    },
    {
        name: 'Iana',
        team: 'Attack',
        ability: 'Gemini Replicator',
        health: 2,
    },
    {
        name: 'IQ',
        team: 'Attack',
        ability: 'Electronics Detector',
        health: 1,
    },
    {
        name: 'Jackal',
        team: 'Attack',
        ability: 'Eyenox Model III',
        health: 2,
    },
    {
        name: 'Jager',
        team: 'Defend',
        ability: 'Magpie Defense System',
        health: 2,
    },
    {
        name: 'Kaid',
        team: 'Defend',
        ability: 'Rtila Electroclaw',
        health: 3,
    },
    {
        name: 'Kali',
        team: 'Attack',
        ability: 'LV Explosive Lance',
        health: 2,
    },
    {
        name: 'Kapkan',
        team: 'Defend',
        ability: 'EDD Booby Trap',
        health: 2,
    },
    {
        name: 'Lesion',
        team: 'Defend',
        ability: 'Gu Mine',
        health: 2,
    },
    {
        name: 'Lion',
        team: 'Attack',
        ability: 'EE-ONE-D',
        health: 2,
    },
    {
        name: 'Maestro',
        team: 'Defend',
        ability: 'Evil Eye',
        health: 3,
    },
    {
        name: 'Maverick',
        team: 'Attack',
        ability: 'Breaching Torch',
        health: 1,
    },
    {
        name: 'Melusi',
        team: 'Defend',
        ability: 'Banshee Sonic Defense',
        health: 1,
    },
    {
        name: 'Mira',
        team: 'Defend',
        ability: 'Black Mirror',
        health: 3,
    },
    {
        name: 'Montagne',
        team: 'Attack',
        ability: 'Extendable Shield',
        health: 3,
    },
    {
        name: 'Mozzie',
        team: 'Defend',
        ability: 'Pest Launcher',
        health: 2,
    },
    {
        name: 'Mute',
        team: 'Defend',
        ability: 'Signal Disruptor',
        health: 2,
    },
    {
        name: 'N0kk',
        team: 'Attack',
        ability: 'HEL Presence Reduction',
        health: 2,
    },
    {
        name: 'Nomad',
        team: 'Attack',
        ability: 'Airjab Launcher',
        health: 2,
    },
    {
        name: 'Oryx',
        team: 'Defend',
        ability: 'Remah Dash',
        health: 2,
    },
    {
        name: 'Osa',
        team: 'Attack',
        ability: 'Talon-8 Clear Shield',
        health: 2,
    },
    {
        name: 'Pulse',
        team: 'Defend',
        ability: 'Heartbeat Sensor',
        health: 1,
    },
    {
        name: 'Rook',
        team: 'Defend',
        ability: 'Armor Pack',
        health: 3, 
    },
    {
        name: 'Sens',
        team: 'Attack',
        ability: 'R.O.U. Projector System',
        health: 3,
    },
    {
        name: 'Sledge',
        team: 'Attack',
        ability: 'Tactical Breaching Hammer',
        health: 2,
    },
    {
        name: 'Smoke',
        team: 'Defend',
        ability: 'Remote Gas Grenade',
        health: 2,
    },
    {
        name: 'Solis',
        team: 'Defend',
        ability: 'Electro Sensor',
        health: 2,
    },
    {
        name: 'Tachanka',
        team: 'Defend',
        ability: 'Grenade Launcher',
        health: 3,
    },
    {
        name: 'Thatcher',
        team: 'Attack',
        ability: 'EMP Grenade',
        health: 2,
    },
    {
        name: 'Thermite',
        team: 'Attack',
        ability: 'Exothermic Charge',
        health: 2,
    },
    {
        name: 'Thorn',
        team: 'Defend',
        ability: 'Razorbloom Shell',
        health: 2,
    },
    {
        name: 'Thunderbird',
        team: 'Defend',
        ability: 'Kona Station',
        health: 1,
    },
    {
        name: 'Twitch',
        team: 'Attack',
        ability: 'Shock Drone',
        health: 2,
    },
    {
        name: 'Valkyrie',
        team: 'Defend',
        ability: 'Black Eye Camera',
        health: 2,
    },
    {
        name: 'Vigil',
        team: 'Defend',
        ability: 'ERC-7',
        health: 1,
    },
    {
        name: 'Wamai',
        team: 'Defend',
        ability: 'Mag-NET',
        health: 2,
    },
    {
        name: 'Warden',
        team: 'Defend',
        ability: 'Glance Smart Glasses',
        health: 2,
    },
    {
        name: 'Ying',
        team: 'Attack',
        ability: 'Candela Device',
        health: 2,
    },
    {
        name: 'Zero',
        team: 'Attack',
        ability: 'ARGUS Launcher',
        health: 2,
    },
    {
        name: 'Zofia',
        team: 'Attack',
        ability: 'KS79 LIFELINE',
        health: 2,
    },
    {
        name: 'Recruit', 
        health: 2,
    },
]