export const weaponList = [
    {
        name: "6P41",
        class: "Primary",
        type: "Light Machine Gun",
        modes: ["Automatic"],
        users: ["Fuze", "Finka"],
        ranges: [25, 40],
        damages: {
            standard: [46, 31],
            suppressed: [39, 28],
        },
        rof: 680,
        mobility: 50,
        mag: 100,
        max: 301,
        reload: {
            empty: 8.5,
            tactical: 8.5,
        },
        ads: {
            normal: 450,
        },
        ammo: "7.62×54mmR",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "9mm-C1",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic"],
        users: ["Frost"],
        ranges: [18, 28],
        damages: {
            standard: [45, 28],
            suppressed: [38, 24],
            extended: [45, 30],
        },
        rof: 575,
        mobility: 50,
        mag: 35,
        max: 205,
        reload: {
            empty: 2.6,
            tactical: 1.9,
        },
        ads: {
            normal: 300,
            angled: 204,
        },
        ammo: "9mm",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Suppressor", "Extended Barrel"],
            grip: ["Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "9x19VSN",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Kapkan", "Tachanka", "Azami"],
        ranges: [18, 28],
        damage: {
            standard: [34, 20],
            suppressed: [28, 17],
        },
        rof: 750,
        mobility: 50,
        mag: 31,
        max: 181,
        reload: {
            empty: 3.2,
            tactical: 2.3,
        },
        ads: {
            normal: 300,
            angled: 204,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: ".44 Mag Semi-Auto",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Nomad", "Kaid"],
        ranges: [12, 22],
        damage: {
            standard: [54, 48],
        },
        rof: 450,
        mobility: 45,
        mag: 8,
        max: 50,
        reload: {
            empty: 2.1,
            tactical: 1.8,
        },
        ads: {
            normal: 200,
        },
        ammo: ".44 AMP",
        attachments: {
            sight: ["Scope 3.0x"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "5.7 USG",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Ash", "Thermite", "Castle", "Pulse", "N0kk", "Zero"],
        ranges: [12, 22],
        damage: {
            standard: [42, 25],
            suppressed: [35, 21],
        },
        rof: 550,
        mobility: 50,
        mag: 21,
        max: 81,
        reload: {
            empty: 2.4,
            tactical: 1.9,
        },
        ads: {
            normal: 200,
        },
        ammo: "FN 5.7x28mm",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "416-C Carbine",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Jager", "Recruit"],
        ranges: [25, 35],
        damage: {
            standard: [38, 21],
            suppressed: [32, 18],
            extended: [38, 32],
        },
        rof: 740,
        mobility: 50,
        mag: 26,
        max: 201,
        reload: {
            empty: 3.4,
            tactical: 2.4,
        },
        ads: {
            normal: 400,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake", "Extended Barrel"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "417",
        class: "Primary",
        type: "Marksman Rifle",
        modes: ["Semi-Automatic"],
        users: ["Twitch", "Lion", "Sens"],
        ranges: [25, 40],
        damage: {
            standard: [69, 45],
            suppressed: [59, 38],
        },
        rof: 450,
        mobility: 50,
        mag: 21,
        max: 161,
        reload: {
            empty: 3.3,
            tactical: 2.6,
        },
        ads: {
            normal: 400,
        },
        ammo: "7.62x51mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Reflex Sight", "Holographic Sight", "Scope 1.5x", "Scope 2.0x", "Scope 2.5x", "Scope 3.0x"],
            barrel: ["Suppressor", "Muzzle Brake", "Flash Hider"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "552 Commando",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["IQ", "Grim"],
        ranges: [25, 35],
        damage: {
            standard: [48, 28],
            suppressed: [40, 24],
        },
        rof: 690,
        mobility: 50,
        mag: 31,
        max: 241,
        reload: {
            empty: 3.1,
            tactical: 2.4,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "556xi",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Thermite", "Osa"],
        ranges: [25, 35],
        damage: {
            standard: [47, 25],
            suppressed: [39, 21],
        },
        rof: 690,
        mobility: 50,
        mag: 31,
        max: 241,
        reload: {
            empty: 3.7,
            tactical: 2.6,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 2.0x", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "1911 TACOPS",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Maverick", "Thorn"],
        ranges: [12, 22],
        damage: {
            standard: [55, 48],
            suppressed: [46, 41],
        },
        rof: 450,
        mobility: 45,
        mag: 9,
        max: 41,
        reload: {
            empty: 2.2,
            tactical: 1.9,
        },
        ads: {
            normal: 200,
        },
        ammo: ".45 ACP",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "ACS12",
        class: "Primary",
        type: "Shotgun",
        modes: ["Automatic"],
        users: ["Maestro", "Alibi", "Azami"],
        ranges: [19, 41],
        damage: {
            standard: [69, 52],
        },
        rof: 300,
        mobility: 50,
        mag: 31,
        max: 91,
        reload: {
            empty: 2.7,
            tactical: 2.0,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "12 Gauge Slugs",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 2.0x"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "AK-12",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Fuze", "Ace"],
        ranges: [25, 35],
        damage: {
            standard: [45, 22],
            suppressed: [37, 19],
        },
        rof: 850,
        mobility: 50,
        mag: 31,
        max: 241,
        reload: {
            empty: 3.4,
            tactical: 2.6,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "5.45x39mm",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 2.0x", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "ALDA 5.56",
        class: "Primary",
        type: "Light Machine Gun",
        modes: ["Automatic"],
        users: ["Maestro"],
        ranges: [25, 40],
        damage: {
            standard: [35, 24],
            suppressed: [29, 20],
        },
        rof: 900,
        mobility: 50,
        mag: 80,
        max: 240,
        reload: {
            empty: 5.7,
            tactical: 6.2,
        },
        ads: {
            normal: 450,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "AR-15.50",
        class: "Primary",
        type: "Marksman Rifle",
        modes: ["Semi-Automatic"],
        users: ["Maverick"],
        ranges: [25, 40],
        damage: {
            standard: [62, 50],
            suppressed: [52, 42],
        },
        rof: 450,
        mobility: 50,
        mag: 11,
        max: 71,
        reload: {
            empty: 3.1,
            tactical: 2.2,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: ".50 Beowulf",
        attachments: {
            sight: ["Red Dot Sight", "Reflex Sight", "Holographic Sight", "Scope 1.5x", "Scope 2.0x", "Scope 2.5x", "Scope 3.0x"],
            barrel: ["Suppressor", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "ARX200",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Nomad", "Iana"],
        ranges: [25, 35],
        damage: {
            standard: [47, 28],
            suppressed: [39, 24],
        },
        rof: 700,
        mobility: 50,
        mag: 21,
        max: 181,
        reload: {
            empty: 3.4,
            tactical: 2.6,
        },
        ads: {
            normal: 400,
        },
        ammo: "7.62x51mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x", "Scope 2.0x", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "AUG A3",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Kaid"],
        ranges: [18, 28],
        damage: {
            standard: [36, 24],
            suppressed: [30, 20],
        },
        rof: 700,
        mobility: 50,
        mag: 32,
        max: 218,
        reload: {
            empty: 3.3,
            tactical: 2.6,
        },
        ads: {
            normal: 300,
            angled: 204,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "AUG A2",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic"],
        users: ["IQ", "Wamai"],
        ranges: [25, 35],
        damage: {
            standard: [42, 26],
            suppressed: [34, 22],
        },
        rof: 720,
        mobility: 50,
        mag: 31,
        max: 241,
        reload: {
            empty: 3.3,
            tactical: 2.6,
        },
        ads: {
            normal: 400,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Bailiff 410",
        class: "Secondary",
        type: "Handgun",
        modes: ["Double-Action"],
        users: ["Maestro", "Alibi", "Oryx", "Doc"],
        ranges: [5, 18],
        damage: {
            standard: [120, 52],
        },
        rof: 485,
        mobility: 50,
        mag: 5,
        max: 35,
        reload: {
            empty: 3.6,
            tactical: 3.4,
        },
        ads: {
            normal: 250,
        },
        ammo: ".410 Bore",
        attachments: {
            sight: ["Red Dot Sight"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Ballistic Shield",
        class: "Primary",
        type: "Ballistic Shield",
        users: ["Fuze"],
        mobility: 30,
    },
    {
        name: "Bearing 9",
        class: "Secondary",
        type: "Machine Pistol",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Hibana", "Echo", "Thunderbird", "Glaz", "Tachanka"],
        ranges: [18, 28],
        damage: {
            standard: [33, 22],
            suppressed: [28, 19],
        },
        rof: 1100,
        mobility: 50,
        mag: 26,
        max: 101,
        reload: {
            empty: 2.7,
            tactical: 1.9,
        },
        ads: {
            normal: 275,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Suppressor", "Flash Hider", "Compensator"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "BOSG.12.2",
        class: "Primary",
        type: "Shotgun",
        modes: ["Break-Action"],
        users: ["Dokkaebi", "Vigil"],
        ranges: [10, 20],
        damage: {
            standard: [125, 80],
        },
        rof: 500,
        mobility: 50,
        mag: 2,
        max: 61,
        reload: {
            empty: 3.0,
            tactical: 2.4,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "12 Gauge Slug",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 2.5x"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "C7E",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Jackal"],
        ranges: [25, 35],
        damage: {
            standard: [42, 21],
            suppressed: [35, 17],
        },
        rof: 800,
        mobility: 50,
        mag: 26,
        max: 201,
        reload: {
            empty: 2.7,
            tactical: 2.0,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 2.0x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "C8-SFW",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Buck"],
        ranges: [25, 35],
        damage: {
            standard: [40, 22],
            suppressed: [37, 18],
            extended: [40, 33],
            skeleton: [480, 304, 120],
        },
        rof: {
            normal: 837,
            skeleton: 220,
        },
        mobility: 50,
        mag: {
            normal: 31,
            skeleton: 6,
        },
        max: {
            normal: 241,
            skeleton: 36,
        },
        reload: {
            empty: 2.9,
            tactical: 2.4,
        },
        ads: {
            normal: 400,
            skeleton: 200,
        },
        ammo: {
            normal: "5.56x45mm NATO",
            skeleton: "12 Gauge Buckshot",
        },
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake", "Extended Barrel"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "C75 Auto",
        class: "Secondary",
        type: "Machine Pistol",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Recruit", "Dokkaebi", "Vigil", "Kali", "Thorn"],
        ranges: [18, 28],
        damage: {
            standard: [35, 23],
            suppressed: [30, 22],
        },
        rof: 1000,
        mobility: 50,
        mag: 27,
        max: 105,
        reload: {
            empty: 2.7,
            tactical: 1.9,
        },
        ads: {
            normal: 275,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            barrel: ["Suppressor"],
        },
    },
    {
        name: "CAMRS",
        class: "Primary",
        type: "Marksman Rifle",
        modes: ["Semi-Automatic"],
        users: ["Buck"],
        ranges: [25, 40],
        damage: {
            standard: [69, 38],
            suppressed: [58, 32],
            skeleton: [480, 304, 120],
        },
        rof: {
            normal: 450,
            skeleton: 220,
        },
        mobility: 50,
        mag: {
            normal: 21,
            skeleton: 6,
        },
        max: {
            normal: 161,
            skeleton: 36,
        },
        reload: {
            empty: 3.4,
            tactical: 2.6,
        },
        ads: {
            normal: 400,
        },
        ammo: {
            normal: "7.62x51mm NATO",
            skeleton: "12 Gauge Buckshot",
        },
        attachments: {
            sight: ["Red Dot Sight", "Reflex Sight", "Holographic Sight", "Scope 1.5x", "Scope 2.0x", "Scope 2.5x", "Scope 3.0x"],
            barrel: ["Suppressor", "Muzzle Brake", "Flash Hider"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Crowd Control Electro Shield",
        class: "Primary",
        type: "Ballistic Shield",
        users: ["Clash"],
    },
    {
        name: "CSRX 300",
        class: "Primary",
        type: "Marksman Rifle",
        modes: ["Bolt-Action"],
        users: ["Kali"],
        ranges: [25, 35],
        damage: {
            standard: [127, 102],
        },
        rof: 50,
        mobility: 50,
        mag: 6,
        max: 36,
        reload: {
            empty: 3.1,
            tactical: 2.5,
        },
        ads: {
            normal: 500,
        },
        ammo: ".300 Winchester Magnum",
    },
    {
        name: "D-50",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Blackbeard", "Valkyrie", "N0kk", "Azami"],
        ranges: [12, 22],
        damage: {
            standard: [71, 35],
        },
        rof: 550,
        mobility: 50,
        mag: 8,
        max: 43,
        reload: {
            empty: 2.5,
            tactical: 2.0,
        },
        ads: {
            normal: 200,
        },
        ammo: ".50 Action Express",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "DP-27",
        class: "Primary",
        type: "Light Machine Gun",
        modes: ["Automatic"],
        users: ["Tachanka"],
        ranges: [24, 40],
        damage: {
            standard: [49, 32],
        },
        rof: 550,
        mobility: 50,
        mag: 70,
        max: 211,
        reload: {
            empty: 4.6,
            tactical: 4.0,
        },
        ads: {
            normal: 450,
        },
        ammo: "7.62x54mmR",
        attachments: {
            sight: ["Red Dot Sight", "Reflex Sight", "Holographic Sight"],
        },
    },
    {
        name: "F2",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Twitch"],
        ranges: [25, 35],
        damage: {
            standard: [37, 22],
            suppressed: [31, 19],
        },
        rof: 980,
        mobility: 50,
        mag: 26,
        max: 201,
        reload: {
            empty: 3.1,
            tactical: 2.4,
        },
        ads: {
            normal: 400,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "F90",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Gridlock"],
        ranges: [25, 35],
        damage: {
            standard: [38, 24],
            suppressed: [32, 20],
        },
        rof: 780,
        mobility: 50,
        mag: 31,
        max: 211,
        reload: {
            empty: 3.1,
            tactical: 2.2,
        },
        ads: {
            normal: 400,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 2.0x", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "SC3000K",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Zero"],
        ranges: [25, 35],
        damage: {
            standard: [45, 29],
            suppressed: [40, 18],
        },
        rof: 800,
        mobility: 50,
        mag: 26,
        reload: {
            empty: 3.4,
            tactical: 2.6,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: ".300 Blackout",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x", "Scope 2.0x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake", "Extended Barrel"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "FMG-9",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Smoke", "N0kk"],
        ranges: [18, 28],
        damage: {
            standard: [34, 18],
        },
        rof: 800,
        mobility: 50,
        mag: 31,
        max: 181,
        reload: {
            empty: 3.0,
            tactical: 2.2,
        },
        ads: {
            normal: 300,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "FO-12",
        class: "Shotgun",
        type: "Shotgun",
        modes: ["Semi-Automatic"],
        users: ["Ela"],
        ranges: [6, 18, 21],
        damage: {
            standard: [280, 192, 96],
            suppressed: [232, 160, 80],
            extended: [280, 232, 136],
        },
        rof: 400,
        mobility: 50,
        mag: 11,
        max: 51,
        reload: {
            empty: 2.4,
            tactical: 3.3,
        },
        ads: {
            normal: 250,
            angled: 170,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Suppressor", "Extended Barrel"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "G8A1",
        class: "Primary",
        type: "Light Machine Gun",
        modes: ["Automatic"],
        users: ["IQ", "Amaru"],
        ranges: [25, 40],
        damage: {
            standard: [37, 28],
            suppressed: [31, 24],
        },
        rof: 850,
        mobility: 50,
        mag: 51,
        max: 301,
        reload: {
            empty: 3.9,
            tactical: 3.0,
        },
        ads: {
            normal: 450,
            angled: 306,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 2.0x", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator"],
            grip: ["Vertical Grip", "Angled Grip"],
        },
    },
    {
        name: "G36C",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Ash", "Iana"],
        ranges: [25, 35],
        damage: {
            standard: [38, 26],
            suppressed: [32, 22],
        },
        rof: 780,
        mobility: 50,
        mag: 31,
        max: 241,
        reload: {
            empty: 3.3,
            tactical: 2.4,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "GONNE-6",
        class: "Secondary",
        type: "Hand Cannon",
        users: ["Glaz", "Buck", "Capitao", "Lion", "Dokkaebi", "Finka", "Gridlock", "Amaru", "Zero", "Sens"],
        damage: {
            standard: 10,
        },
        mobility: 50,
        mag: 1,
        max: 1,
    },
    {
        name: "GSh-18",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Fuze", "Kapkan", "Tachanka", "Finka", "Flores"],
        ranges: [12, 22],
        damage: {
            standard: [44, 24],
            suppressed: [37, 20],
        },
        rof: 550,
        mobility: 50,
        mag: 19,
        max: 73,
        reload: {
            empty: 2.3,
            tactical: 2.1,
        },
        ads: {
            normal: 200,
            shield: 600,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
        },
    },
    {
        name: "ITA12L",
        class: "Primary",
        type: "Shotgun",
        modes: ["Pump-Action"],
        users: ["Jackal", "Mira", "Solis"],
        ranges: [2, 12],
        damage: {
            standard: [400, 240],
        },
        rof: 85,
        mobility: 50,
        mag: 8,
        max: 41,
        ads: {
            normal: 250,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "ITA12S",
        class: "Secondary",
        type: "Shotgun",
        modes: ["Pump-Action"],
        users: ["Jackal", "Mira", "Frost", "Amaru"],
        ranges: [1, 12],
        damage: {
            standard: [560, 120],
        },
        rof: 85,
        mobility: 50,
        mag: 5,
        max: 26,
        ads: {
            normal: 250,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Laser"],
        },
    },
    {
        name: "K1A",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Vigil"],
        ranges: [18, 28],
        damage: {
            standard: [36, 24],
            suppressed: [30, 20],
        },
        rof: 720,
        mobility: 50,
        mag: 31,
        max: 241,
        reload: {
            empty: 3.0,
            tactical: 2.7,
        },
        ads: {
            normal: 300,
            angled: 204,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Keratos .357",
        class: "Secondary",
        type: "Handgun",
        modes: ["Double-Action"],
        users: ["Maestro, Alibi, Wamai"],
        ranges: [12, 22],
        damage: {
            standard: [78, 65],
            suppressed: [66, 55],
        },
        rof: 450,
        mobility: 45,
        mag: 6,
        max: 54,
        reload: {
            empty: 4.0,
        },
        ads: {
            normal: 200,
        },
        ammo: ".357 Magnum",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "L85A2",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Recruit", "Sledge", "Thatcher"],
        ranges: [25, 35],
        damage: {
            standard: [47, 29],
            suppressed: [39, 25],
        },
        rof: 670,
        mobility: 50,
        mag: 31,
        max: 241,
        reload: {
            empty: 3.3,
            tactical: 2.7,
        },
        ads: {
            normal: 400,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x", "Scope 2.0x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "LFP586",
        class: "Secondary",
        type: "Handgun",
        modes: ["Double-Action"],
        users: ["Twitch", "Montagne", "Lion", "Doc", "Rook", "Kaid"],
        ranges: [12, 22],
        damage: {
            standard: [78, 34],
        },
        rof: 550,
        mobility: 45,
        mag: 6,
        max: 42,
        reload: {
            empty: 4.0,
        },
        ads: {
            normal: 200,
            shield: 600,
        },
        ammo: ".357 Magnum",
        attachments: {
            underBarrel: ["Laser"],
        },
    },
    {
        name: "LMG-E",
        class: "Primary",
        type: "Light Machine Gun",
        modes: ["Automatic"],
        users: ["Zofia"],
        ranges: [25, 40],
        damage: {
            standard: [41, 26],
            suppressed: [29, 23],
        },
        rof: 720,
        mobility: 50,
        mag: 150,
        max: 300,
        reload: {
            empty: 6.5,
            tactical: 7.1,
        },
        ads: {
            normal: 450,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x", "Scope 2.0x", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Luison",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Caveira"],
        ranges: [12, 35],
        damage: {
            standard: [65, 13],
        },
        rof: 450,
        mobility: 50,
        mag: 13,
        max: 91,
        reload: {
            empty: 2.6,
            tactical: 1.9,
        },
        ads: {
            normal: 200,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            barrel: ["Suppressor"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "M4",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Maverick"],
        ranges: [25, 35],
        damage: {
            standard: [44, 27],
            suppressed: [37, 23],
        },
        rof: 750,
        mobility: 50,
        mag: 31,
        max: 181,
        reload: {
            empty: 3.4,
            tactical: 2.6,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake", "Extended Barrel"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "M12",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Caveira"],
        ranges: [18, 28],
        damage: {
            standard: [40, 31],
            suppressed: [34, 26],
            extended: 40,
        },
        rof: 550,
        mobility: 50,
        mag: 31,
        max: 181,
        reload: {
            empty: 3.0,
            tactical: 2.2,
        },
        ads: {
            normal: 300,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Holographic Sight", "Red Dot Sight", "Reflex Sight"],
            barrel: ["Suppressor", "Flash Hider", "Muzzle Brake", "Extended Barrel"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "M45 MEUSOC",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Ash", "Thermite", "Pulse"],
        ranges: [12, 22],
        damage: {
            standard: [58, 33],
            suppressed: [49, 28],
        },
        rof: 550,
        mobility: 50,
        mag: 8,
        max: 57,
        reload: {
            empty: 1.9,
            tactical: 1.6,
        },
        ads: {
            normal: 200,
        },
        ammo: ".45 ACP",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "M249",
        class: "Primary",
        type: "Light Machine Gun",
        modes: ["Automatic"],
        users: ["Recruit", "Capitao"],
        ranges: [25, 40],
        damage: {
            standard: [48, 32],
        },
        rof: 650,
        mobility: 50,
        mag: 100,
        max: 401,
        reload: {
            empty: 7.6,
        },
        ads: {
            normal: 450,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x", "Scope 2.0x", "Scope 2.5x"],
            barrel: ["Flash Hider", "Compensator"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "M249 SAW",
        class: "Primary",
        type: "Light Machine Gun",
        modes: ["Automatic"],
        users: ["Gridlock"],
        ranges: [25, 40],
        damage: {
            standard: [48, 32],
        },
        rof: 650,
        mobility: 50,
        mag: 60,
        max: 240,
        reload: {
            empty: 4.5,
            tactical: 3.3,
        },
        ads: {
            normal: 450,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x", "Scope 2.0x", "Scope 2.5x"],
            barrel: ["Flash Hider", "Compensator"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "M590A1",
        class: "Primary",
        type: "Shotgun",
        modes: ["Pump-Action"],
        users: ["Sledge", "Thatcher", "Smoke", "Mute", "Warden"],
        ranges: [8, 13],
        damage: {
            standard: [384, 160],
        },
        rof: 85,
        mobility: 50,
        mag: 7,
        max: 36,
        ads: {
            normal: 250,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "M762",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Zofia"],
        ranges: [25, 35],
        damage: {
            standard: [45, 23],
            suppressed: [38, 20],
        },
        rof: 730,
        mobility: 50,
        mag: 31,
        max: 241,
        reload: {
            empty: 3.3,
            tactical: 2.6,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "7.62x39mm",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 2.0x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "M870",
        class: "Primary",
        type: "Shotgun",
        modes: ["Pump-Action"],
        users: ["Recruit", "Jager", "Bandit", "Thorn"],
        ranges: [3, 12],
        damage: {
            standard: [480, 160],
        },
        rof: 100,
        mobility: 50,
        mag: 7,
        max: 36,
        ads: {
            normal: 250,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "M1014",
        class: "Primary",
        type: "Shotgun",
        modes: ["Semi-Automatic"],
        users: ["Thermite", "Castle", "Pulse", "Ace"],
        ranges: [6, 10, 19],
        damage: {
            standard: [272, 232, 120],
        },
        rof: 200,
        mobility: 50,
        mag: 8,
        max: 33,
        ads: {
            normal: 250,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Mk19mm",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Buck", "Frost", "Iana"],
        ranges: [12, 22],
        damage: {
            standard: [48, 27],
            suppressed: [42, 23],
        },
        rof: 550,
        mobility: 50,
        mag: 14,
        max: 66,
        reload: {
            empty: 1.9,
            tactical: 1.6,
        },
        ads: {
            normal: 200,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Mk 14 EBR",
        class: "Primary",
        type: "Marksman Rifle",
        modes: ["Semi-Automatic"],
        users: ["Recruit", "Dokkaebi", "Aruni"],
        ranges: [25, 35],
        damage: {
            standard: [60, 51],
            suppressed: [51, 43],
        },
        rof: 450,
        mobility: 50,
        mag: 21,
        max: 101,
        reload: {
            empty: 3.4,
            tactical: 3.1,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "7.62x51mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x", "Scope 2.0x", "Scope 2.5x", "Scope 3.0x"],
            barrel: ["Suppressor", "Muzzle Brake", "Flash Hider"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Mk17 CQB",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Blackbeard"],
        ranges: [25, 35],
        damage: {
            standard: [40, 26],
            suppressed: [34, 22],
            extended: [40, 29],
        },
        rof: 585,
        mobility: 50,
        mag: 21,
        max: 161,
        reload: {
            empty: 3.1,
            tactical: 2.4,
        },
        ads: {
            normal: 400,
            shield: 550,
            angled: 272,
            angledShield: 330,
        },
        ammo: "7.62x51mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake", "Extended Barrel"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "MP5",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Doc", "Rook", "Melusi"],
        ranges: [18, 28],
        damage: {
            standard: [27, 18],
            suppressed: [22, 15],
        },
        rof: 800,
        mobility: 50,
        mag: 31,
        max: 181,
        reload: {
            empty: 2.9,
            tactical: 2.2,
        },
        ads: {
            normal: 300,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x", "Scope 2.0x"],
            barrel: ["Suppressor", "Flash Hider", "Muzzle Brake"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "MP5K",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Recruit", "Mute", "Wamai"],
        ranges: [18, 28],
        damage: {
            standard: [30, 22],
            suppressed: [25, 19],
        },
        rof: 800,
        mobility: 50,
        mag: 31,
        max: 181,
        reload: {
            empty: 2.8,
            tactical: 2.0,
        },
        ads: {
            normal: 300,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "MP5SD",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Echo"],
        ranges: [18, 28],
        damage: {
            standard: [30, 18],
        },
        rof: 800,
        mobility: 50,
        mag: 31,
        max: 181,
        reload: {
            empty: 2.9,
            tactical: 2.2,
        },
        ads: {
            normal: 300,
            angled: 204,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "MP7",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Bandit", "Zero"],
        ranges: [18, 28],
        damage: {
            standard: [32, 20],
            suppressed: [28, 17],
        },
        rof: 900,
        mobility: 50,
        mag: 31,
        max: 181,
        reload: {
            empty: 2.8,
            tactical: 2.2,
        },
        ads: {
            normal: 300,
        },
        ammo: "HK 4.6x30mm",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "MPX",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Valkyrie", "Warden"],
        ranges: [18, 28],
        damage: {
            standard: [26, 19],
            suppressed: [21, 16],
        },
        rof: 830,
        mobility: 50,
        mag: 31,
        max: 181,
        reload: {
            empty: 3.1,
            tactical: 2.4,
        },
        ads: {
            normal: 300,
            angled: 204,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Mx4 Storm",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Alibi"],
        ranges: [18, 28],
        damage: {
            standard: [26, 19],
            suppressed: [22, 16],
            extended: [26, 23],
        },
        rof: 950,
        mobility: 50,
        mag: 31,
        max: 181,
        reload: {
            empty: 3.1,
            tactical: 2.8,
        },
        ads: {
            normal: 300,
            angled: 204,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake", "Extended Barrel"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "OTs-03",
        class: "Primary",
        type: "Marksman Rifle",
        modes: ["Semi-Automatic"],
        users: ["Glaz"],
        ranges: [25, 40],
        damage: {
            standard: [71, 59],
            suppressed: [64, 50],
        },
        rof: 380,
        mobility: 36,
        mag: 16,
        max: 76,
        reload: {
            empty: 3.4,
            tactical: 2.7,
        },
        ads: {
            normal: 400,
        },
        ammo: "7.62x54mmR",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Suppressor", "Muzzle Brake", "Flash Hider"],
        },
    },
    {
        name: "P90",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Doc", "Rook", "Solis"],
        ranges: [18, 28],
        damage: {
            standard: [22, 18],
            suppressed: [18, 15],
            extended: 22,
        },
        rof: 970,
        mobility: 50,
        mag: 51,
        max: 251,
        reload: {
            empty: 2.9,
            tactical: 2.4,
        },
        ads: {
            normal: 300,
        },
        ammo: "FN 5.7x28mm",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Muzzle Brake", "Extended Barrel"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "P9",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Recruit", "Twitch", "Montagne", "Doc", "Rook", "Lion", "Ace"],
        ranges: [12, 22],
        damage: {
            standard: [45, 27],
            suppressed: [38, 23],
        },
        rof: 550,
        mobility: 45,
        mag: 17,
        max: 81,
        reload: {
            empty: 2.1,
            tactical: 1.8,
        },
        ads: {
            normal: 200,
            shield: 600,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "P-10C",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Clash", "Warden"],
        ranges: [12, 22],
        damage: {
            standard: [40, 25],
            suppressed: [34, 21],
        },
        rof: 450,
        mobility: 45,
        mag: 16,
        max: 106,
        reload: {
            empty: 2.2,
            tactical: 1.9,
        },
        ads: {
            normal: 200,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight"],
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "P10 RONI",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Mozzie", "Aruni"],
        ranges: [18, 28],
        damage: {
            standard: [26, 19],
            suppressed: [22, 16],
        },
        rof: 980,
        mobility: 50,
        mag: 16,
        max: 201,
        reload: {
            empty: 2.7,
            tactical: 1.7,
        },
        ads: {
            normal: 300,
            angled: 204,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake", "Extended Barrel"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "P12",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Recruit", "Blitz", "IQ", "Jager", "Bandit", "Wamai"],
        ranges: [12, 22],
        damage: {
            standard: [44, 24],
            suppressed: [37, 20],
        },
        rof: 550,
        mobility: 50,
        mag: 16,
        max: 76,
        reload: {
            empty: 2.4,
            tactical: 1.9,
        },
        ads: {
            normal: 200,
            angled: 600,
        },
        ammo: ".45 ACP",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "P226 Mk 25",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Sledge", "Thatcher", "Smoke", "Mute", "Kali"],
        ranges: [12, 22],
        damage: {
            standard: [50, 30],
            suppressed: [42, 25],
        },
        rof: 550,
        mobility: 50,
        mag: 16,
        max: 61,
        reload: {
            empty: 2.1,
            tactical: 1.8,
        },
        ads: {
            normal: 200,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "P229",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Hibana", "Echo", "Goyo", "Grim"],
        ranges: [12, 22],
        damage: {
            standard: [51, 28],
            suppressed: [46, 23],
        },
        rof: 550,
        mobility: 50,
        mag: 13,
        max: 61,
        reload: {
            empty: 2.1,
            tactical: 1.8,
        },
        ads: {
            normal: 200,
        },
        ammo: ".357 SIG",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "PARA-308",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Capitao"],
        ranges: [25, 35],
        damage: {
            standard: [48, 29],
            suppressed: [42, 25],
            extended: [48, 39],
        },
        rof: 650,
        mobility: 50,
        mag: 31,
        max: 241,
        reload: {
            empty: 3.3,
            tactical: 2.6,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "7.62x51mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake", "Extended Barrel"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "PDW9",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Jackal", "Osa"],
        ranges: [18, 28],
        damage: {
            standard: [34, 26],
            suppressed: [28, 22],
        },
        rof: 800,
        mobility: 50,
        mag: 51,
        max: 301,
        reload: {
            empty: 3.4,
            tactical: 2.6,
        },
        ads: {
            normal: 300,
            angled: 204,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "PMM",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Glaz", "Fuze", "Finka", "Kapkan", "Tachanka", "Osa"],
        ranges: [12, 22],
        damage: {
            standard: [63, 29],
            suppressed: [53, 25],
        },
        rof: 550,
        mobility: 50,
        mag: 9,
        max: 49,
        reload: {
            empty: 1.9,
            tactical: 1.4,
        },
        ads: {
            normal: 200,
            shield: 600,
        },
        ammo: "9x18mm Makarov",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "POF-9",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Sens"],
        ranges: [25, 35],
        damage: {
            standard: [35, 21],
            suppressed: [29, 17],
            extended: [35, 27],
        },
        rof: 740,
        mobility: 50,
        mag: 51,
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x", "Scope 2.0x", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake", "Extended Barrel"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "PRB92",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Capitao", "Nomad", "Aruni"],
        ranges: [12, 22],
        damage: {
            standard: [42, 25],
            suppressed: [38, 20],
        },
        rof: 450,
        mobility: 50,
        mag: 16,
        max: 91,
        reload: {
            empty: 2.6,
            tactical: 1.9,
        },
        ads: {
            normal: 200,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Q-929",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Ying", "Lesion", "Thunderbird"],
        ranges: [12, 22],
        damage: {
            standard: [60, 30],
            suppressed: [42, 25],
        },
        rof: 550,
        mobility: 50,
        mag: 11,
        max: 61,
        reload: {
            empty: 2.1,
            tactical: 1.8,
        },
        ads: {
            normal: 200,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "R4-C",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Ash"],
        ranges: [25, 35],
        damage: {
            standard: [39, 25],
            suppressed: [36, 21],
            extended: [39, 35],
        },
        rof: 860,
        mobility: 50,
        mag: 31,
        max: 241,
        reload: {
            empty: 3.4,
            tactical: 2.7,
        },
        ads: {
            normal: 400,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake", "Extended Barrel"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "RG15",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Zofia", "Ela", "Melusi"],
        ranges: [12, 22],
        damage: {
            standard: [38, 22],
            suppressed: [32, 20],
        },
        rof: 550,
        mobility: 45,
        mag: 16,
        max: 61,
        reload: {
            empty: 2.4,
            tactical: 1.9,
        },
        ads: {
            normal: 200,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight"],
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "SASG-12",
        class: "Primary",
        type: "Shotgun",
        modes: ["Semi-Automatic"],
        users: ["Finka", "Kapkan"],
        ranges: [2, 15],
        damage: {
            standard: [400, 112],
            suppressed: [336, 80],
        },
        rof: 330,
        mobility: 50,
        mag: 11,
        max: 51,
        reload: {
            empty: 2.9,
            tactical: 3.4,
        },
        ads: {
            normal: 250,
            angled: 170,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Suppressor"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Scorpion EVO 3 A1",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Ela"],
        ranges: [18, 28],
        damage: {
            standard: [23, 15],
            suppressed: [20, 14],
        },
        rof: 1080,
        mobility: 50,
        mag: 41,
        max: 251,
        reload: {
            empty: 3.0,
            tactical: 2.1,
        },
        ads: {
            normal: 300,
            angled: 204,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "SDP 9mm",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Gridlock", "Mozzie", "Sens"],
        ranges: [12, 22],
        damage: {
            standard: [47, 25],
            suppressed: [39, 21],
        },
        rof: 450,
        mobility: 45,
        mag: 17,
        max: 81,
        reload: {
            empty: 2.2,
            tactical: 1.4,
        },
        ads: {
            normal: 200,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "SG-CQB",
        class: "Primary",
        type: "Shotgun",
        modes: ["Pump-Action"],
        users: ["Twitch", "Lion", "Doc", "Rook", "Grim"],
        ranges: [5, 12],
        damage: {
            standard: [424, 208],
        },
        rof: 85,
        mobility: 50,
        mag: 7,
        max: 36,
        ads: {
            normal: 250,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "SIX12",
        class: "Primary",
        type: "Shotgun",
        modes: ["Double-Action"],
        users: ["Ying"],
        ranges: [6, 11],
        damage: {
            standard: [280, 192],
        },
        rof: 200,
        mobility: 50,
        mag: 6,
        max: 36,
        reload: {
            empty: 2.7,
        },
        ads: {
            normal: 250,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "SIX12 SD",
        class: "Primary",
        type: "Shotgun",
        modes: ["Double-Action"],
        users: ["Lesion", "N0kk"],
        ranges: [6, 11],
        damage: {
            standard: [280, 192],
        },
        rof: 200,
        mobility: 50,
        mag: 6,
        max: 36,
        reload: {
            empty: 2.7,
        },
        ads: {
            normal: 250,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "SMG-11",
        class: "Secondary",
        type: "Machine Pistol",
        modes: ["Automatic"],
        users: ["Recruit", "Smoke", "Mute", "Amaru", "Solis"],
        ranges: [18, 28],
        damage: {
            standard: [35, 23],
            suppressed: [30, 20],
            extended: [35, 26],
        },
        rof: 1270,
        mobility: 50,
        mag: 17,
        max: 97,
        reload: {
            empty: 2.9,
            tactical: 2.0,
        },
        ads: {
            normal: 275,
        },
        ammo: ".45 ACP",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Extended Barrel"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "SMG-12",
        class: "Secondary",
        type: "Machine Pistol",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Dokkaebi", "Vigil", "Warden"],
        ranges: [18, 28],
        damage: {
            standard: [28, 19],
        },
        rof: 1270,
        mobility: 50,
        mag: 33,
        max: 193,
        reload: {
            empty: 3.0,
            tactical: 2.0,
        },
        ads: {
            normal: 275,
            angled: 187,
        },
        ammo: ".380 ACP",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "SPAS-12",
        class: "Primary",
        type: "Shotgun",
        modes: ["Semi-Automatic"],
        users: ["Valkyrie", "Oryx"],
        ranges: [4, 11, 20],
        damage: {
            standard: [280, 216, 160],
        },
        rof: 200,
        mobility: 50,
        mag: 7,
        max: 36,
        ads: {
            normal: 250,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "SPAS-15",
        class: "Primary",
        type: "Shotgun",
        modes: ["Semi-Automatic"],
        users: ["Caveira", "Thunderbird"],
        ranges: [4, 11, 20],
        damage: {
            standard: [240, 184, 128],
        },
        rof: 290,
        mobility: 50,
        mag: 7,
        max: 37,
        reload: {
            empty: 2.1,
            tactical: 3.2,
        },
        ads: {
            normal: 250,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Spear .308",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Finka", "Thunderbird"],
        ranges: [25, 35],
        damage: {
            standard: [42, 26],
            suppressed: [36, 23],
        },
        rof: 700,
        mobility: 50,
        mag: 31,
        max: 241,
        reload: {
            empty: 3.3,
            tactical: 2.4,
        },
        ads: {
            normal: 400,
        },
        ammo: "7.62x51mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 2.0x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "SPSMG9",
        class: "Secondary",
        type: "Machine Pistol",
        modes: ["Automatic"],
        users: ["Clash", "Kali"],
        ranges: [18, 28],
        damage: {
            standard: [33, 22],
            suppressed: [28, 19],
        },
        rof: 980,
        mobility: 50,
        mag: 21,
        max: 161,
        reload: {
            empty: 2.7,
            tactical: 2.2,
        },
        ads: {
            normal: 275,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Reflex Sight", "Holographic Sight"],
            barrel: ["Suppressor", "Flash Hider"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "SR-25",
        class: "Primary",
        type: "Marksman Rifle",
        modes: ["Semi-Automatic"],
        users: ["Blackbeard", "Flores"],
        ranges: [25, 40],
        damage: {
            standard: [61, 35],
            suppressed: [52, 30],
        },
        rof: 450,
        mobility: 38,
        mag: 21,
        max: 101,
        reload: {
            empty: 3.5,
            tactical: 2.9,
        },
        ads: {
            normal: 400,
            shield: 550,
        },
        attachments: {
            sight: ["Red Dot Sight", "Reflex Sight", "Holographic Sight", "Scope 1.5x", "Scope 2.0x", "Scope 2.5x", "Scope 3.0x"],
            barrel: ["Suppressor", "Muzzle Flash", "Flash Hider"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Super 90",
        class: "Primary",
        type: "Shotgun",
        modes: ["Semi-Automatic"],
        users: ["Frost", "Melusi"],
        ranges: [4, 19],
        damage: {
            standard: [280, 104],
        },
        rof: 200,
        mobility: 50,
        mag: 8,
        max: 33,
        ads: {
            normal: 250,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "SuperNova",
        class: "Primary",
        type: "Shotgun",
        modes: ["Pump-Action"],
        users: ["Hibana", "Echo", "Amaru"],
        ranges: [8, 13],
        damage: {
            standard: [384, 160],
        },
        rof: 75,
        mobility: 50,
        mag: 7,
        max: 55,
        ads: {
            normal: 250,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Suppressor"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Super Shorty",
        class: "Secondary",
        type: "Shotgun",
        modes: ["Pump-Action"],
        users: ["Recruit", "Castle", "Clash", "Gridlock"],
        ranges: 12,
        damage: {
            standard: [280, 120],
        },
        rof: 85,
        mobility: 50,
        mag: 3,
        max: 45,
        ads: {
            normal: 250,
        },
        ammo: "12 Gauge Buckshot",
        attachments: {
            sight: ["Red Dot Sight"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "T-5 SMG",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Lesion", "Oryx"],
        ranges: [18, 28],
        damage: {
            standard: [28, 19],
            suppressed: [24, 16],
        },
        rof: 900,
        mobility: 50,
        mag: 31,
        max: 241,
        reload: {
            empty: 3.0,
            tactical: 2.4,
        },
        ads: {
            normal: 300,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "G52-Tactical Light Shield",
        class: "Primary",
        type: "Ballistic Shield",
        users: ["Blitz"],
        mobility: 30,
    },
    {
        name: "TCSG12",
        class: "Primary",
        type: "Shotgun",
        modes: ["Semi-Automatic"],
        users: ["Kaid", "Goyo"],
        ranges: [17, 40],
        damage: {
            standard: [63, 47],
            suppressed: [53, 37],
        },
        rof: 450,
        mobility: 50,
        mag: 11,
        max: 61,
        reload: {
            empty: 3.2,
            tactical: 2.5,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "12 Gauge Slug",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 2.0x"],
            barrel: ["Suppressor"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Type-89",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Hibana"],
        ranges: [25, 35],
        damage: {
            standard: [40, 25],
            suppressed: [37, 21],
        },
        rof: 850,
        mobility: 50,
        mag: 21,
        max: 181,
        reload: {
            empty: 3.3,
            tactical: 2.6,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "UMP45",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Castle", "Pulse"],
        ranges: [18, 28],
        damage: {
            standard: [38, 23],
            suppressed: [32, 19],
        },
        rof: 600,
        mobility: 50,
        mag: 26,
        max: 176,
        reload: {
            empty: 2.9,
            tactical: 2.4,
        },
        ads: {
            normal: 300,
            angled: 204,
        },
        ammo: ".45 ACP",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake", "Extended Barrel"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "USP40",
        class: "Secondary",
        type: "Handgun",
        modes: ["Semi-Automatic"],
        users: ["Jackal", "Mira", "Oryx"],
        ranges: [12, 22],
        damage: {
            standard: [48, 25],
            suppressed: [41, 21],
        },
        rof: 550,
        mobility: 50,
        mag: 13,
        max: 61,
        reload: {
            empty: 2.1,
            tactical: 1.8,
        },
        ads: {
            normal: 200,
        },
        ammo: ".40 S&W",
        attachments: {
            barrel: ["Suppressor", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "UZK50GI",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "Semi-Automatic"],
        users: ["Thorn"],
        ranges: [18, 28],
        damage: {
            standard: [44, 26],
            suppressed: [37, 22],
        },
        rof: 700,
        mobility: 50,
        mag: 23,
        max: 177,
        ads: {
            normal: 300,
            angled: 204,
        },
        ammo: ".50 GI",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "V308",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Lion"],
        ranges: [18, 28],
        damage: {
            standard: [44, 28],
            suppressed: [37, 21],
        },
        rof: 700,
        mobility: 50,
        mag: 51,
        max: 201,
        reload: {
            empty: 3.3,
            tactical: 2.6,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "7.62x51mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 2.0x", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Vector .45 ACP",
        class: "Primary",
        type: "Submachine Gun",
        modes: ["Automatic", "2-Round Burst", "Semi-Automatic"],
        users: ["Mira", "Goyo"],
        ranges: [18, 28],
        damage: {
            standard: [23, 16],
            suppressed: [19, 13],
            extended: [23, 20],
        },
        rof: 1200,
        mobility: 50,
        mag: 26,
        max: 176,
        reload: {
            empty: 2.8,
            tactical: 2.0,
        },
        ads: {
            normal: 300,
        },
        ammo: ".45 ACP",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake", "Extended Barrel"],
            grip: ["Vertical Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "AK-74M",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Nomad"],
        ranges: [25, 35],
        damage: {
            standard: [44, 26],
            suppressed: [37, 22],
        },
        rof: 650,
        mobility: 50,
        mag: 41,
        max: 281,
        reload: {
            empty: 3.4,
            tactical: 2.6,
        },
        ads: {
            normal: 400,
        },
        ammo: "5.45x39mm",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "AR33",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "2-Round Burst", "Semi-Automatic"],
        users: ["Thatcher", "Flores"],
        ranges: [25, 35],
        damage: {
            standard: [41, 24],
            suppressed: [35, 20],
        },
        rof: 749,
        mobility: 50,
        mag: 26,
        max: 201,
        reload: {
            empty: 3.3,
            tactical: 2.6,
        },
        ads: {
            normal: 400,
            angled: 272,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x", "Scope 2.0x", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "Commando 9",
        class: "Primary",
        type: "Assault Rifle",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Mozzie"],
        ranges: [18, 28],
        damage: {
            standard: [36, 24],
            suppressed: [30, 20],
        },
        rof: 780,
        mobility: 50,
        mag: 26,
        max: 176,
        reload: {
            empty: 2.5,
            tactical: 2.0,
        },
        ads: {
            normal: 300,
            angled: 204,
        },
        ammo: "9x19mm Parabellum",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
    {
        name: "T-95 LSW",
        class: "Primary",
        type: "Light Machine Gun",
        modes: ["Automatic", "3-Round Burst", "Semi-Automatic"],
        users: ["Ying"],
        ranges: [25, 40],
        damage: {
            standard: [46, 32],
            suppressed: [41, 26],
        },
        rof: 650,
        mobility: 50,
        mag: 81,
        max: 241,
        reload: {
            empty: 3.0,
            tactical: 2.0,
        },
        ads: {
            normal: 450,
            angled: 306,
        },
        ammo: "5.56x45mm NATO",
        attachments: {
            sight: ["Red Dot Sight", "Holographic Sight", "Reflex Sight", "Scope 1.5x", "Scope 2.0x", "Scope 2.5x"],
            barrel: ["Suppressor", "Flash Hider", "Compensator", "Muzzle Brake"],
            grip: ["Vertical Grip", "Angled Grip"],
            underBarrel: ["Laser"],
        },
    },
]